name: language_quest
description: A language learning app with gamification.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Navigation
  go_router: ^14.2.7

  # Network & API
  dio: ^5.7.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.0
  json_annotation: ^4.9.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/mascots/
    - assets/images/backgrounds/
    - assets/images/ui_elements/
    - assets/animations/

  fonts:
    - family: GameFont
      fonts:
        - asset: assets/fonts/CrystalUniverse-Oblique.ttf